!DEC$ FREEFORM 
! BANDS.f90-
! THIS PROGRAM COMPUTES, FOR UP TO 10 BANDS OF AN INPUT FILE(SPECTRA
! OR TIME DATA), 6 QUANTITIES COLLECTIVELY DESCRIBING THE ACTIVITY IN
! EACH BAND. BANDS CAN OVERLAP. OUTPUT ORDER: PEAK AMPLITUDE, MEAN
! AMPLITUDE, AMPLITUDE SD, AND MEAN, SD, AND PEAK LOCATION WITH RESPECT
! TO THE ABSCISSA DIMENSION(FREQUENCY OR TIME), INDEP. OF AMPLITUDE.
! NOTE- BANDS BECOMES UNDEPENDABLE FOR INPUT WAVEFORMS CONCAVE AWAY FROM
! THE ABSCISSA; THIS MIGHT HAPPEN WITH EVOKED POTENTIAL COMPONENTS,
! FOR EXAMPLE.

SUBROUTINE BANDS
	INCLUDE 'MAX.INC'
	DIMENSION Q(6)
! Q(1) = peak amplitude
! Q(2) = mean amplitude
! Q(3) = SD of amplitude
! Q(4) = abscissa-weighted mean over the band (estimate of peak time)
! Q(5) = SD of estimate of peak time
! Q(6) = actual time of peak value in band
	COMMON IFLAG1,IFLAG2,IFLAG3,KNT,ISZ,ICHAN(ICHMAX)
	COMMON/DEV/ITI,IXO
	COMMON/FLDES/NG,NA,NC,ND,NF,NP,NR,IS,IBUF(IOMAX)
	COMMON/FLDESO/NGO,NAO,NCO,NDO,NFO,NPO,NRO,ISO,IBUFO(IOMAX)
	INTEGER*4, SAVE :: NB,NSTART(10),IT,NTOT(10)
	REAL*4, SAVE :: VNS(10),BND(20)
	EQUIVALENCE (X,IX)
	SAVE nso,dx,ic
	INTEGER SELGRPS(20)
	CHARACTER*24 LINESEL(20)
	COMMON /SELGVS/ SELGRPS,LINESEL
	COMMON /CPN/ CURPROCNAME
	CHARACTER*10 CURPROCNAME
	LOGICAL WPPSF
	SAVE WPPSF
	CHARACTER*1024 OUTNAME
	CHARACTER*1024 OUTFNM
    CHARACTER*256 ALINE
    CHARACTER*32 BLINE
    
	IF(IFLAG1)10,20,30
    
10	NFO=3
	CURPROCNAME='BANDS'
	WRITE(*,*) CURPROCNAME
! MOVE CHANNEL LABELS
	J=6*NGO+109
	DO 15 I=1,NCO
	    L=J+5
	    K=6*(NG+ICHAN(I))-5
	    DO 14 M=J,L
	        IBUFO(M)=IBUF(K)
14	        K=K+1
15	    J=J+6
!     DEFAULTS
	IT=0
	ITYPE=1
	NB=0
	WPPSF=.TRUE.
	CALL DoBANDSDialog(ITYPE,IT,NB,WPPSF)
	GOTO (1,2) ITYPE
!     DETERMINE SPACING OF DATA POINTS
!     IS=SAMPLE RATE FOR TIME DATA, MAX FREQUENCY FOR SPECTRA
1	DX=1.0/FLOAT(IS)
	GO TO 3
2	DX=FLOAT(IS)/FLOAT(ND-1)  ! spectra have dc term as first point
3   K=1
    WRITE(*,'(1X,I2,A)') NB, " bands:"
    DO 5 I=1,NB
        READ(LINESEL(I),*) P1
        READ(LINESEL(I+10),*) PN
        WRITE(BLINE,'(I2,A1,F6.2,A1,F6.2,A1)') I,":",P1,"-",PN,";"
        LEN = LEN_TRIM(BLINE)
        ALINE(K:K+LEN-1) = BLINE(1:LEN)
        K=K+LEN
	    NSTART(I)=P1/DX + 1
	    NTOT(I) = (PN - P1) / DX + 0.5 ! number of points in band
	    VNS(I)=P1
5	    CONTINUE
    WRITE(*,*) ALINE(1:K-2)
	IT=IT+1
	NDO=6*NB
	NSO=NGO+NAO+1
	ISZ=12*NB
    IF(ITYPE.EQ.1)THEN
        WRITE(*,*) "Time series"
    ELSE
        WRITE(*,*) "Frequency spectrum"
    END IF
    IF(IT.NE.1) THEN
        SELECT CASE(IT)
        CASE(2)
            WRITE(*,*) "Transform: SQRT"
        CASE(3)
            WRITE(*,*) "Transform: LN"
        CASE(4)
            WRITE(*,*) "Transform: ASIN"
        CASE(5)
            WRITE(*,*) "Transform: ABS"
        END SELECT
    ENDIF
	IF(WPPSF)THEN
        WRITE(*,*) "Write SYSTAT file"
	    OUTNAME=OUTFNM(CURPROCNAME)
	    LTRO=LEN_TRIM(OUTNAME)
	    OUTNAME(LTRO-2:LTRO)='syd'
	    CALL ADVMOPEN(OUTNAME)
	    CALL SYSWHB(IBUFO,108,IBUFO(109),NB,NGO,NCO)
	ENDIF
	IC=0 ! current channel number
	RETURN
    
! EXECUTION PHASE
    
20  N=NSO
	IC=IC+1
	IF(IC.GT.NCO) IC=1
	IF(IC.EQ.1.AND.WPPSF) CALL SYD1BANDSSAVE(NB,NCO,NGO) ! Header for all channels
	DO 50 L=1,NB ! for each band
! INITIALIZE OUTPUT VARS; FIND FLOOR AND CEILING
	    DO 25 I=1,6
25          Q(I)=0.0
	    J=NSTART(L) ! starting point for this band
	    CALL XVAL(J,XV,XI)
	    CEIL=RECODE(XV,IT) ! CEIL is maximum value in band
	    BASE1=CEIL ! BASE1 is minimum value in band
	    NTB=NTOT(L) ! number of points in this band
	    NMAX=1
	    NMIN=1
	    DO 60 I=2,NTB
	        J=J+1
	        CALL XVAL(J,XV,XI)
	        X=RECODE(XV,IT)
	        IF(X-CEIL)52,52,51
51	        CEIL=X
	        NMAX=I
	        GO TO 60
52	        IF(BASE1-X)60,60,53
53	        BASE1=X
	        NMIN=I
60	        CONTINUE
	    Q(1)=CEIL
	    BASE=AMIN1(BASE1,0.0)  ! MAY CHANGE THIS, ************ make dependent on ITYPE
! CHECK FOR DEGENERACY
	    IF(BASE1.EQ.CEIL)GO TO 62
! REVERSE FOR NEGATIVE-GOING PEAKS(DIFFERENCE SPECTRA, TIME DATA)
	    IF(ABS(CEIL)-ABS(BASE1))61,63,63 ! ************ make dependent on ITYPE
61	    Q(1)=BASE1
	    BASE=AMAX1(CEIL,0.0)   ! AND THIS, TO ADJUST FOR BASELINE !  ************ make dependent on ITYPE
	    NMAX=NMIN
	    GO TO 63
! DEGENERATE CASE; MAX=MIN, ALL VALUES EQUAL
62	    Q(2)=Q(1)
	    Q(3)=0.0
	    Q(4)=FLOAT(NTB+1)/2.
	    NMAX=IFIX(Q(4)+.5) !NEAREST INTEGER
	    Q(5)=SQRT(FLOAT(NTB*NTB-1)/12.) !MAGIC FOR SEQUENCE OF INTEGERS
	    GO TO 70
63	    J=NSTART(L)
	    V1=1.0
	    DO 35 I=1,NTB
	        CALL XVAL(J,XV,XI)
	        PT1=RECODE(XV,IT) - BASE
	        TX=ABS(PT1) !  ************ make dependent on ITYPE
	        Q(2)=Q(2)+PT1
	        Q(3)=Q(3)+PT1*PT1
	        Q(4)=Q(4)+TX*V1
	        Q(5)=Q(5)+TX*V1*V1
	        Q(6)=Q(6)+TX          !SUM OF DATA VALUES
	        J=J+1
	        V1=V1+1.0
35	        CONTINUE
! COMPUTE VARS
38	    AN=NTB
	    Q(2)=Q(2)/AN
	    Q(3)=SQRT(Q(3)/AN - Q(2)*Q(2))
	    Q(4)=Q(4)/Q(6)
	    Q(5)=SQRT(Q(5)/Q(6)-Q(4)*Q(4))
! CONVERT LAST 2 VARS TO INPUT SCALE UNITS
70	    Q(4)=VNS(L)+(Q(4)-1.0)*DX
	    Q(5)=Q(5)*DX
	    Q(6)=VNS(L)+FLOAT(NMAX-1)*DX  !ADD A VAR FOR PEAK FREQ OR LATENCY
! MOVE TO OUTPUT BUFFER
	    DO 45 I=1,6
	        X=Q(I)
45          IBUFO((I-1)*NB+N)=IX
        N=N+1
	    IF(WPPSF)CALL SYD2BANDSSAVE(Q,NCO)          ! Data for every channel
50  CONTINUE
    CALL PUTSTD(IBUFO)
    IF(IC.EQ.NCO.AND.WPPSF)CALL ENDSYDREC               ! End record
    RETURN
    
30  IF(WPPSF)CALL ADVMCLSE
    RETURN
	END
