!DEC$ FREEFORM 
! CHDIFF.FOR- TAKES DIFFERENCE BETWEEN SPECIFIED PAIRS OF CHANNELS, IN
! SPECIFIED ORDER. MIGHT BE GENERALIZED TO LET A CHANNEL BE INVOLVED
! IN MULTIPLE DIFFERENCES. NEEDS ALLOCATED FLOATING WORKSPACE 8/93.
SUBROUTINE CHDIFF
	INCLUDE 'MAX.INC'
	COMMON/DEV/ITI
	COMMON IFLAG1,IFLAG2,IFLAG3,KNT,ISZ,ICHAN(ICHMAX)
	COMMON /FLDES/NG,NA,NC,ND,NF,NP,NR,IS,IBUF(IOMAX)
	COMMON /FLDESO/NGO,NAO,NCO,NDO,NFO,NPO,NRO,ISO,IBUFO(IOMAX)
	DIMENSION LIST(ICHMAX)
	INTEGER*4, SAVE :: NREC,NCIN,IT,NSO,LIST1(ICHMAX)
	EQUIVALENCE (IX,X),(IY,Y),(IZ,Z)
	character*255 ALINE
	COMMON /CPN/ CURPROCNAME
	CHARACTER*10 CURPROCNAME
	
	IF(IFLAG1)10,30,60
	
10	NCIN=NCO
	CURPROCNAME='CHDIFF'
	WRITE(*,*) CURPROCNAME
	NFO=3
! SUCCESSIVE PAIRS IN LIST ARE THE CHANNEL PAIRS; LIST1 CONTAINS OFFSETS
! AND CONTROLS SKIPPING OF UNUSED CHANNELS, IF ANY. INPUT CHANNELS
! STORED IN IBUFO IN THE ORDER IN WHICH THEY'LL BE NEEDED
1	DO 2 I=1,16
	LIST(I)=0
2	LIST1(I)=-1
5	CONTINUE
	CALL DoCHDIFFDialog(ICHAN,NCO1,LIST,IT)
	
	DO 25 K=1,16
	IF(LIST(K))26,26,21
21	DO 25 J=1,NCIN
	IF(LIST(K)-ICHAN(J))25,24,25
24	LIST1(J)=K-1
25	CONTINUE
300	FORMAT('REQUEST FOR UNAVAILABLE INPUT CHANNEL(#=',I2,')')
	WRITE(ALINE,300)LIST(K)
	CALL ShowInfoText('Error',ALINE)
	GO TO 10
26	NSO=NGO+NAO+1
	ISZ=NGO+NAO+NDO*NCO
	NCO=NCO1
	IT=IT+1
	NREC=0
	RETURN
	
30	NREC=NREC+1
	IOFF=LIST1(IBUF(1))
	IF(IOFF)60,31,31
31	J=NSO+IOFF*NDO
	DO 35 I=1,NDO
	CALL XVAL(I,XV,XI)
	X=RECODE(XV,IT)
	IBUFO(J)=IX
35	J=J+1
	IF(NREC-NCIN)60,40,40
! WAIT TILL ALL RECORDS IN BEFORE FORMING DIFFERENCES
40	NREC=0
	DO 55 I=1,NCO
	IBUFO(1)=I
	K=NSO
	J1=NSO+(I-1)*2*NDO
	J2=J1+NDO
	DO 50 JI=1,NDO
	IX=IBUFO(J1)
	IY=IBUFO(J2)
	Z=X-Y
	IBUFO(K)=IZ
	K=K+1
	J1=J1+1
50	J2=J2+1
	CALL PUTSTD(IBUFO)
55	CONTINUE
60	RETURN
END
