!DEC$ FREEFORM 
! MAGPH.f90- PROGRAM TO READ INPUT FILE OF COMPLEX FOURIER COEFFICIENTS
! AND WRITE OUTPUT FILE OF MAGNITUDES AND/OR PHASES. USED FOR EXAMPLE
! TO GENERATE AUTOSPECTRA FROM XFORM, OR PHASE INFO FROM COMPLEX
! VALUES OUTPUT BY XSPEC.

SUBROUTINE MAGPH

    INCLUDE 'MAX.INC'
	DIMENSION XC(2)
	COMMON IFLAG1,IFLAG2,IFLAG3,KNT,ISZ,ICHAN(ICHMAX)
	COMMON/FLDES/NG,NA,NC,ND,NF,NP,NR,IS,IBUF(IOMAX)
	COMMON/FLDESO/NGO,NAO,NCO,NDO,NFO,NPO,NRO,ISO,IBUFO(IOMAX)
	COMPLEX CXY,TXY
	INTEGER*4, SAVE :: NSO,J1,K1,NDO2,NPB,IMAG,IPH,ITAP
	REAL*4, SAVE :: AN
    INTEGER*4 :: K2
	EQUIVALENCE (X,IX),(Y,IY),(Z,IZ)
	EQUIVALENCE (CXY,XC),(XC(1),X),(XC(2),Y)
    COMMON /CPN/ CURPROCNAME
    CHARACTER*10 CURPROCNAME
    
	IF(IFLAG1)10,20,30

10	NFO=3
    CURPROCNAME='MAGPH'

! MOVE CHANNEL LABELS

    J=6*NGO+109
	DO 12 I=1,NCO
	L=J+5
	K=6*(NG+ICHAN(I))-5
	DO 15 I1=J,L
	    IBUFO(I1)=IBUF(K)
15	    K=K+1
12	J=J+6

! GET START INDEX AND # OUTPUT POINTS

13  CALL DoMAGPHDialog(IMAG,IPH,J1,NDO2,NPB,ITAP,NDO)
	IF(IMAG+IPH .EQ. 0) GOTO 13
	IF(NDO2*NPB .GT. NDO) GOTO 13
	NDO=(IMAG+IPH)*NDO2
	NSO=NGO+NAO+1
	AN=NPB
	K1=NSO+NDO2
	ISZ=NDO
	RETURN

20	K=NSO
	K2=K1
	L=J1
	DO 60 I=1,NDO2
! COMPUTE NEEDED QUANTITIES FOR THIS BLOCK
	    TXY=0.0
	    DO 50 J=1,NPB
	        CALL XVAL(L,X,Y) !equivalent to CXY
	        TXY=TXY+CXY
50	        L=L+1

! STORE BLOCK VALUES
        CXY=TXY
	    IF(IMAG)55,55,51
51	    Z=SQRT(X*X+Y*Y)/AN
	    IF(ITAP)53,53,52
52	    Z=Z*1.185185185
53	    IBUFO(K)=IZ
	    K=K+1
55	    IF(IPH)60,60,56
56	    Z=ATAN2(Y,X)

!C POSITIVE ANGLE IMPLIES X LEADS Y IF INPUT CAME FROM XSPEC
	    IBUFO(K2)=IZ
60	    K2=K2+1
	CALL PUTSTD(IBUFO)
    
30	RETURN
END

