!DEC$ FREEFORM 
! PLOT.F90- GENERAL PURPOSE PLOTTING ROUTINE FOR FILMAN. INITIALLY
! MODIFIED 10/91 TO ABSORB AXIS LABELING AND OTHER IMPROVEMENTS FROM
! SPECTR. CONVERTED TO MICROSOFT FORTRAN/GRAPHICS 10/92. COULD BE 
! GENERALIZED TO IDENTIFY VIDEO CONFIGURATION & CALCULATE ALL NECESSARY
! PLOT PARAMETERS, FOR PORTABILITY. MODIFIED 7/93 TO ADD MULTICHANNEL
! CAPABILITY. STILL NEEDS VERTICAL LABELS, BETTER TREATMENT OF
! IMPLICIT DECIMATION WITH LONG RECORDS AND/OR MULTICHANNEL PLOTS,
! AND POSSIBLY SCROLLING MULTICHANNEL DISPLAY OF LONG DATA RECORDS.
SUBROUTINE PLOT
	USE IFQWIN
	USE IFCORE
	INCLUDE 'MAX.INC'
! BASIC SCREEN DIMENSIONS FOR SELECTED VIDEO MODE; MUST BE DETERMINED
! INDIVIDUALLY FOR EACH COMPUTER
	PARAMETER (MARGIN=20)      
	INTEGER*2 ROWS   ! ROWS IS PARAMETER FOR SETVIDEOMODE
	CHARACTER*8 CLAB
	CHARACTER*15 RECSET
	CHARACTER*24 INPFIL,CTITLE,POINTS
	CHARACTER*24 CLABEL(ICHMAX),CTEMP     ! FOR PS VERSION
	CHARACTER*116 BLANKS
	CHARACTER*4 BLANK4(29)
	CHARACTER*1 IA
	INTEGER*2 IX0,IY0,IYOFF
	INTEGER*4, SAVE :: NRK,N1,NP1,NXEQ,ISF,MODE,INEXT,M,NCTP
	INTEGER*4, SAVE :: ICLABS(6,ICHMAX),ISTART(ICHMAX,2)
	RECORD/RCCOORD/ S
	RECORD/WINDOWCONFIG/ WC
	RECORD/QWINFO/ WINFO
	COMMON IFLAG1,IFLAG2,IFLAG3,KNT,ISZ,ICHAN(ICHMAX)
	COMMON/FLDES/ NG,NA,NC,NP,NF,NL,NR,IS,IBUF(IOMAX)
	COMMON/FLDESO/ NGO,NAO,NCO,NDO,NFO,NLO,NRO,ISO,IBUFO(IOMAX)
	COMMON/STDFIL/INPFIL
	COMMON/DEV/ITI,ILP,IGRAPH
	COMMON/PTLST/NLIST,LIST(2,72)
	COMMON/PLOTDATA/IPL,NPT,IT,XDIM,XSCALE,YDIM,YSCALE,X1,DX, &
	            JMP,ISCL,IAXIS,YMAX,YMIN,IX0,IY0,IYOFF,CLAB
	DIMENSION WORK(IOMAX-120)
	EQUIVALENCE (ICLABS,CLABEL),(WORK,IBUFO(121)),(BLANKS,BLANK4)
	DATA BLANK4/29*'    '/
	DATA ROWS /60/    ! CHANGE THIS IF TEXT AT TOP LOOKS WEIRD
	INTEGER*2 IXDIM,IYDIM
	integer*2 isx,isy
	type(windowconfig) :: wco
	COMMON /IGHWND/ IGRAPHHWND,ISX,ISY
	character*1 key
	EXTERNAL WINVER
	INTEGER WINVER
	COMMON /CPN/ CURPROCNAME
	CHARACTER*10 CURPROCNAME
	save x0,iusrscly
    
!************************************************************************
	IF(IFLAG1) 10,20,3000
10	IFLAG3=0
	CURPROCNAME='PLOT'
	WRITE(*,*) CURPROCNAME
    
!   OPEN GRAPHICS WINDOW FOR PLOTTING
	OPEN(UNIT=IGRAPH,FILE='USER',TITLE='PLOT')
	igraphHwnd=GetHwndQQ(IGRAPH)
	CALL SETTEXTWINDOW(1,1,3,120)
	I=INITIALIZEFONTS()
	ISTAT=SETFONT("t'tms rmn'h18w9")
	I=SETBKCOLORRGB(Z'00FFFFFF')
	I=SETCOLORRGB(0)
	I=SETTEXTCOLORRGB(0)
	WINFO%TYPE=QWIN$MAX
	I=SETWSIZEQQ(IGRAPH,WINFO)
	IF(WINVER().GE.7)THEN
	    CALL MGetWindowSize(igraphHwnd,IW1,IH1)
	    isx=IW1-32
	    isy=IH1-64
	ELSE
	    Ltemp=GETWINDOWCONFIG(wco)
	    isx=wco%numxpixels
	    isy=wco%numypixels
	ENDIF
	I=FOCUSQQ(5)  !SEND FOCUS BACK TO CONSOLE WINDOW
	IXDIM=isx
	IYDIM=isy
	IX0=MARGIN+1
	IY0=IYDIM-MARGIN-1
	ISF=0
	NRK=0
	NXEQ=0
	ISZ=0
	N1=1              ! FIRST LIST POINT
	NP1=LIST(1,1)     ! CORRESPONDING DATA POINT
	NPT=NDO
	INEXT=0
	IT=1
	NCTP=NCO                            ! TOTAL CHANS TO PLOT
	M=1                                 ! CURRENT-CHANNEL POINTER
	MODE=1                              ! FULL-SCREEN/SINGLE
	IYOFF=0                              ! OFFSET FOR CSA'S
	CLAB='       '
	iusrscly=0
	! GET CHANNEL LABELS
	DO 15 I=1,NCO
	    K=6*(NG+ICHAN(I))-5
	    DO 15 J=1,6
	        ICLABS(J,I)=IBUF(K)
15	        K=K+1
	NRS=NR/NC
	CALL DoPlotTypeDialog(ISUPRE,ISUPCH,IPMOD,IPTYP,NRS.LE.1,NCO.EQ.1)
	IF(ISUPRE.EQ.1)GOTO 145
11	ISF=1
	WRITE(RECSET,'(A)') '(SUPERIMPOSED)'
14	IF(NCO.EQ.1) GO TO 12
	MODE=2
	GO TO 17
145	IF(NCO.EQ.1) GO TO 12
	IF(ISUPCH.EQ.1)GOTO 16
	ISF=2
	WRITE(CTITLE,'(A)') '(CHANNELS SUPERIMPOSED)'
	GO TO 12
16	CONTINUE
	MODE=IPMOD
	IF(MODE.EQ.1) GO TO 12
17	WRITE(CTITLE,'(A)') '(MULTICHANNEL PLOT)'
!     SET UP GRAPHICS WINDOW AND ESTABLISH MAXIMUM SIZE
12	CONTINUE
	IPL=IPTYP
	CALL SETUP(IXDIM,IYDIM,MARGIN,CLABEL,NCO,MODE,ISTART,XDIM,YDIM)
	XSCALE=XDIM/FLOAT(NPT-1)   ! # PIXELS/DX, EXACT
	IF(IPL.EQ.2) GO TO 55
50	YDIM=YDIM/2.0
	IF(IPL.EQ.3)GO TO 55
	DX=1.0/FLOAT(IS)
	X0=DX*FLOAT(LIST(1,1))
	GO TO 551
55	DX=FLOAT(IS)/FLOAT(NP-1)  ! NEED TO ALLOW FOR DC TERM IN SPECTRA
	X0=DX*FLOAT(LIST(1,1)-1)  ! ACTUAL VALUE IN XSCALE UNITS AT PT 1
551	X1=X0
	JMP=1       ! ON FIRST ENTRY PLOT ALL POINTS
	RETURN
    
! EXECUTION PHASE CODE STARTS HERE; FIRST CHECK FOR NEW RECSET

20	I=FOCUSQQ(IGRAPH)
	IF(KNT-NRK)90,2002,2001  
2001	NRK=KNT
	IF(NXEQ)30,30,35
    
! VERY FIRST SELECTED RECSET; ESTABLISH DESIRED PLOT REGIME

30	CALL CLEARSCREEN(0)
! FIND INITIAL VERTICAL SCALE
	if(iusrscly.ne.0) goto 561
	CALL XVAL(1,XV,XI)
	YMIN=RECODE(XV,IT)
	YMAX=ABS(YMIN)
	DO 56 I=N1,N1+NPT-1
	    CALL XVAL(I,XV,XI)
	    VAL=RECODE(XV,IT)
	    IF(ABS(VAL).GT.YMAX) YMAX=ABS(VAL)
	    IF(VAL.LT.YMIN) YMIN=VAL
56	    CONTINUE
	IF(IPL.NE.2) YMIN=0.     ! FORCES SPECTRAL PLOTS TO START AT 0 AMP, TOO
561	YMAX0=YMAX   ! SAVE FOR LATER SCALE FIDDLING
	YSCALE=YDIM/(YMAX-YMIN)
	IAXIS=1     ! GENERATE AXES
	M=1         ! FIRST CHANNEL
	ISCL=0      ! DON'T SCALE THE DATA
	GO TO 22
    
! NEW RECSET AFTER PLOT REGIME ACCEPTED
35	M=1
	IF(ISF.NE.1) CALL CLEARSCREEN(0)
	IF(ISF.EQ.1) IAXIS=0
	GO TO 22
    
! NEW CHANNEL, SAME RECORDSET
2002	IF(MODE.EQ.1 .AND. ISF.NE.2)CALL CLEARSCREEN(0)
22	IX0=ISTART(M,1)
	IY0=ISTART(M,2)
	K=1
	DO 221 I=N1,N1+NPT-1       ! DON'T USE JMP HERE
	    CALL XVAL(I,XV,XI)
	    WORK(K)=RECODE(XV,IT)
221 	K=K+1
	IF(MODE.NE.2)GO TO 222
	CTEMP=CLABEL(M)
	CLAB=CTEMP(1:8)
222 CALL PLOTCHAN
    
! KEY CONTROL SECTION HERE!
	IF(NXEQ)71,71,41
41	IF(MODE.EQ.2 .OR. ISF.EQ.2)GO TO 42
	GO TO(71,90)ISF+1
42	M=M+1
	IF(M-NCTP)90,90,71
! LABEL PLOT WITH FILENAME, RECSET NUMBER, ETC
71	CALL SETTEXTPOSITION(2,3,S)
	CALL OUTTEXT('FILE:'//TRIM(INPFIL))
	IF(ISF.EQ.1)GO TO 721
	WRITE(RECSET,700)KNT
700	FORMAT('RECORD-SET:',I3)
721	CONTINUE !CALL SETTEXTPOSITION(2,21,S)
	CALL OUTTEXT(' '//RECSET)
	IF(MODE.EQ.2 .OR. ISF.EQ.2)GO TO 74
	WRITE(CTITLE,701)ICHAN(M),CLABEL(M)
701	FORMAT('CHANNEL ',I2,':',A12)
74	CALL OUTTEXT(' '//TRIM(CTITLE))
	WRITE(POINTS,800)NP1,NP1+NPT-1
800	FORMAT(' POINTS:',I4,'-',I4)
	CALL OUTTEXT(' '//TRIM(POINTS))
	CALL SETTEXTPOSITION(1,3,S)
	IF(NXEQ)45,45,44
44	IF(MODE.EQ.1 .AND. NCO.GT.1)M=M+1   !UPDATE CHANNEL COUNTER 
! WAIT FOR <CR>
45	CONTINUE
	IARES=INEXT
69	CALL DoPlotAdvanceDialog(IARES)
	IF(IARES.EQ.2)THEN
    	read(IGRAPH,'(A)')KEY
	    IARES=0
	    GOTO 69
	ENDIF
107	FORMAT(1X)
	IF(IARES.EQ.1)THEN
	    KNT=INT(NR/NC)!-1   ! Jump to the last record
	    IFLAG1=1
	ENDIF
	IF(INEXT.EQ.1) GO TO 90  ! INEXT = RETURN, AFTER PLOT LAYOUT ACCEPTED
! FIRST PLOT IS TRIAL; CHECK FOR NEW SCALE, TRANSFORM, PLOT REGION, DECIMATION
	CALL SETTEXTPOSITION(1,3,S)
	Y0MAX=YMAX0
	J0MP=JMP
	I0SKP=NPT/INT(XDIM)
	N01=NP1
	N0P=NP1+NPT-1
	IXFORM=IT-1
	CALL DoPlotAdjustDialog(ICHGF,IXFORM,Y0MAX,J0MP,I0SKP,N01,N0P)
! NO MORE CHANGES
29	IF(ICHGF.NE.0)GOTO 500
	NXEQ=1      ! NXEQ SET TO 1 ONLY AFTER PLOT LAYOUT ACCEPTED
	M=M+1       ! DONE HERE FOR FIRST PLOT ONLY
	ISCL=0       ! ASSUME CONSTANT SCALE FOR ALL SUPERIMPOSITION CASES
	IF(ISF.NE.0)GO TO 291
	CALL DoPlotScalingDialog(ISCMOD)
	ISCL=ISCMOD
291	INEXT=1 !SO WE SKIP REWORK FROM HERE ON
	GO TO 90
! CHANGE TO PLOT A SUBSET OF THE ORIGINALLY SELECTED POINTS
500	IF((ICHGF.AND.Z'01').EQ.0)GOTO 600
	P1=N01
	PN=N0P
	IF(IPL.GE.2) GO TO 5004
	P1=P1+DX
5004	N1=(P1-X0)/DX + 1  
	NL=(PN-X0)/DX + 1
	NPT=NL-N1+1
	X1=P1
	XSCALE=XDIM/FLOAT(NPT-1)
600	IF((ICHGF.AND.Z'02').EQ.0)GOTO 60
	IT=IXFORM
	IT=IT+1
60	IF((ICHGF.AND.Z'04').EQ.0)GOTO 400
	Y2=Y0MAX
	IF(Y2.LE.0.)Y2=YMAX0
	YMAX=Y2
	YMAX0=YMAX
	YSCALE=YDIM/(YMAX-YMIN)
	iusrscly=1
! CHANGE TO PLOT ONLY SAMPLING FRACTION OF AVAILABLE POINTS
400	IF((ICHGF.AND.Z'08').EQ.0)GOTO 441
	ISKP=NPT/INT(XDIM)      ! MAXIMUM DECIMATION FACTOR
	JMP=J0MP
441	CALL CLEARSCREEN(0)
	GO TO 30
90  RETURN
    
! TERMINATION SECTION

3000	CONTINUE
	CLOSE(IGRAPH)
	RETURN
END
    
! *******************************************************************
! PLOTCHAN.FOR- SUBROUTINE TO PLOT ONE RECORD FOR FILMAN PLOT ROUTINE
! WITH MULTICHANNEL CAPABILITY
SUBROUTINE PLOTCHAN
	USE IFQWIN
	INCLUDE 'MAX.INC'
	RECORD/XYCOORD/XY
	COMMON/FLDESO/IDO(8),IBUFO(IOMAX)
	COMMON/PLOTDATA/IPL,NPT,IT,XDIM,XSCALE,YDIM,YSCALE,X1,DX, &
	JMP,ISCL,IAXIS,YMAX,YMIN,IX0,IY0,IYOFF,CLAB
	DIMENSION WORK(IOMAX-120)
	CHARACTER*5 XLAB
	CHARACTER*8 CLAB
! POWERSTATION GRAPHICS ROUTINES STILL EXPECT INT*2 SCREEN COORDS,
! WHICH IS A BIG PAIN
	INTEGER*2 JPL,IX0,IY0,IYOFF,IYTOP,IYLAB,IXDIM,IYDIM,ICX,ICY
	INTEGER*2 IX1,IY1,TWO,THREE,ELEVEN,IXL,ISTAT
	EQUIVALENCE (IBUFO(121),WORK) ! PRESUMED DATA LOCATION FOR NOW
	DATA TWO,THREE,ELEVEN/2,3,11/
    
! *******************************************************************
	IXDIM=XDIM
	IYDIM=YDIM
	IYLAB=IY0+5
	XSCALDATA=XSCALE*FLOAT(JMP) ! CORRECTION FOR VARIABLE DECIMATION
	IF(IPL.EQ.2) GO TO 40
50	JPL=IY0-IYDIM
	GO TO 55
40	JPL=IY0
55	IYTOP=JPL-IYDIM         !???
	ICX=IX0+IXDIM-80
	ICY=IYTOP+6
! *******************************************************************
! TEST WHETHER DATA SCALING NEEDED      
	IF(ISCL.EQ.0)GO TO 21
	VAL=RECODE(WORK(1),IT) !FIND MAXIMUM/MINIMUM
	YMAX=ABS(VAL)
	YMIN=VAL
	DO 56 I=2,NPT,JMP
	VAL=RECODE(WORK(I),IT)
	IF (ABS(VAL).GT.YMAX) YMAX=ABS(VAL)
	IF(VAL.LT.YMIN)YMIN=VAL
56	CONTINUE
	IF(IPL.NE.2) YMIN=0.     ! FORCE SPECTRA TO START AT 0 AMPLITUDE
	YSCALE=YDIM/(YMAX-YMIN)
! *************************************************************AXES
! TEST WHETHER WE NEED TO DRAW AXES ETC
21	IF(IAXIS.NE.1) GO TO 22
	XLAB='        '
! FIRST DRAW AXES
	CALL MOVETO(IX0,JPL,XY)  !X-AXIS
	ISTAT = LINETO(IX0+IXDIM,JPL)
	CALL MOVETO(IX0,IY0,XY)  !Y-AXIS
	ISTAT=LINETO(IX0,IYTOP)
! LABEL X-AXIS
	CALL LABSCL(IPL,NPT,DX,XDIM,STEP,XINT)  ! CHOOSES LABEL REGIME
	IF(IPL.NE.3) GO TO 2110
	CALL MOVETO(IX0,IY0,XY)
	ISTAT=LINETO(IX0+IXDIM,IY0)
2110	XV1=X1                 ! VALUE AT FIRST PLOT POINT
	XVN=XV1+FLOAT(NPT-1)*DX  ! VALUE AT LAST PLOT POINT
	FTCK=(XVN-XV1)/STEP   ! EXACT # STEPS
	XSCAL2=XDIM/(FTCK)    ! PIXELS/STEP, EXACT
! IF NECESSARY, ADJUST POSITION OF FIRST TICK TO A STEP BOUNDARY
	IOFF=0
	FRACT=STEP-AMOD(XV1,STEP)
	IF(FRACT.EQ.STEP)GO TO 75 ! ALREADY ON A BOUNDARY
	XV1=XV1+FRACT  ! VALUE AT FIRST TICK
	IOFF=IFIX((FRACT/STEP)*XSCAL2+.5)    ! PIXEL OFFSET TO FIRST TICK
! OFFSET CORRECTION IS (STEP FRACTION)*(PIXELS/STEP)
75	IX1=IX0+IOFF
	XI=IX1
	NTCK=INT(FTCK)+1
	XDAT=XV1
	DO 90 I=1,NTCK
	CALL MOVETO(IX1,JPL-TWO,XY)
	ISTAT=LINETO(IX1,JPL+THREE)
	IF(IPL.EQ.2)GO TO 751
	CALL MOVETO(IX1,IY0-TWO,XY)
	ISTAT=LINETO(IX1,IY0+THREE)
751	IF(AMOD(XDAT,XINT))85,80,85
80	CALL MOVETO(IX1,JPL+THREE,XY)
	ISTAT=LINETO(IX1,JPL+ELEVEN)
	IF(IPL.EQ.2)GO TO 752
	CALL MOVETO(IX1,IY0+THREE,XY)
	ISTAT=LINETO(IX1,IY0+ELEVEN)
752	IF(IPL.NE.1) GO TO 8002
! patch for short time segments- convert to ms.
	IF(FLOAT(NPT)*DX .GE. .5) GO TO 8001
	IXD1=IFIX(XDAT*1000.+.5)
	WRITE(XLAB,8011)IXD1
8011	FORMAT(I5)
	GO TO 803
8001	WRITE(XLAB,8010)XDAT   
8010	FORMAT(F5.2)
	GO TO 803
8002	IXDAT=XDAT
	WRITE(XLAB,81)IXDAT    
81	FORMAT(I4)
803	IXL=IX1-24  !START POSITION FOR LABEL
	CALL MOVETO(IXL,IYLAB,XY)
	CALL OUTGTEXT(XLAB)
85	XI=XI+XSCAL2
	IX1=XI+.5
	XDAT=XDAT+STEP
90	CONTINUE
! *******************************************************************
! DRAW NEXT PLOT
22	IX1=IX0
	JPL1=JPL-IYOFF
	Y=(RECODE(WORK(1),IT)-YMIN)*YSCALE
	IF(ABS(Y).GT.YDIM) Y=SIGN(YDIM,Y)
	IY1=MAX0(INT4(JPL1-IFIX(Y)),INT4(IYTOP))
	XI=IX1
	CALL MOVETO(IX1,IY1,XY)
	DO 70 I=2,NPT,JMP
	XI=XI+XSCALDATA
	IX1=XI+.5
	Y=(RECODE(WORK(I),IT)-YMIN)*YSCALE
	IF(ABS(Y).GT.YDIM) Y=SIGN(YDIM,Y)
	IY1=MAX0(INT4(JPL1-IFIX(Y)),INT4(IYTOP))     ! LIMIT PLOT HEIGHT,
	ISTAT=LINETO(IX1,IY1)             ! WITH OFFSET POSSIBLE
70	CONTINUE
! LABEL PLOT WITH ABBREVIATED CHANNEL LABEL
	CALL MOVETO(ICX,ICY,XY)
	CALL OUTGTEXT(CLAB)
	RETURN
END
