	SUBROUTINE PTSEL  ! SELECTS TIME WINDOW ON INPUT DATA

	COMMON/FLDES/NG,NA,NC,ND,NF,NP,NR,IS,IBUF(1)

	COMMON/DEV/ITI,ILP,IO3,IO4

	COMMON/PTLST/NLIST,LIST(2,72),NP1,NP2,NPTOT,P1,PT

	CHARACTER*1 IA

	IF(NPTOT.EQ.0)GO TO 1

	WRITE(ITI,101)P1,PT

101     FORMAT('$   PTSEL: START=',F7.3,', LENGTH=',F7.3,'; CHANGE? >'\)

	READ(ITI,201)IA

	IF(IA.NE.'Y')RETURN

1       WRITE(ITI,100)

100     FORMAT('$   PTSEL: FIRST, LAST POINTS IN SECONDS >'\)

	READ(ITI,*)P1,PN

	IF(PN.GT.FLOAT(ND)/IS)GO TO 1 ! QUICK CHECK ON PTS VS. SECS

	NP1=P1*FLOAT(IS) + 1

	NP2=PN*FLOAT(IS)

	PT=PN-P1

	NPTOT=PT*FLOAT(IS)

	IF(NP2.GT.ND)GO TO 1

	WRITE(ITI,200)NP1,NP2,NPTOT

200     FORMAT('$    FIRST=',I5,'; LAST=',I5,'; N=',I5,'; OK? >'\)

	READ(ITI,201)IA

201     FORMAT(A1)

	IF(IA.EQ.'N')GO TO 1

	RETURN

	END

